var app=angular.module('app',['ngRoute','angularMoment']);
app.config(function($routeProvider){
$routeProvider
.when('/dashboard',{
  templateUrl:'partials/dashboard.html'
})
.when('/products',{
  templateUrl:'partials/products.html'
})
.when('/customers',{
  templateUrl:'partials/customers.html'
})
.when('/orders',{
  templateUrl:'partials/orders.html'
})
.otherwise({
  redirectTo:'/dashboard'
})
})
